import { NextResponse } from 'next/server'

const U='https://imjzkiwgkvrxafqweeei.supabase.co'
const K='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltanpraXdna3ZyeGFmcXdlZWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY1NTY4MTQsImV4cCI6MjEwMjEzMjgxNH0.Iii9aQqBAMBAk7ru5rD0VDpLXro6ZERSoBZgL0t2gbQ'
const H={apikey:K,Authorization:`Bearer ${K}`}
type R={id:string;round_number:number}
type M={id:string;round_id:string;home_team:string;away_team:string;home_score:number;away_score:number}
type P={id:string;name:string;sort_order:number}
type Pr={match_id:string;player_id:string;home_score:number;away_score:number}
async function db<T>(p:string,i?:RequestInit):Promise<T>{const r=await fetch(`${U}/rest/v1/${p}`,{...i,headers:{...H,...(i?.headers||{})},cache:'no-store'});if(!r.ok)throw new Error(await r.text());const t=await r.text();return(t?JSON.parse(t):undefined)as T}
const out=(h:number,a:number)=>Math.sign(h-a)
const pts=(p:Pr,m:M)=>p.home_score===m.home_score&&p.away_score===m.away_score?3:out(p.home_score,p.away_score)===out(m.home_score,m.away_score)?1:0
async function group(){return(await db<{chat_id:number}[]>('bot_chats?select=chat_id&is_primary=eq.true&limit=1'))[0]?.chat_id}
async function send(chat:number,text:string){const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw new Error('token missing');const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chat,text,parse_mode:'HTML'})});if(!r.ok)throw new Error(await r.text())}
function label(o:number,m:M){return o>0?`победу ${m.home_team}`:o<0?`победу ${m.away_team}`:'ничью'}
async function digest(r:R){const[ps,ms,prs,allMs]=await Promise.all([db<P[]>('players?select=id,name,sort_order&order=sort_order.asc'),db<M[]>(`matches?select=id,round_id,home_team,away_team,home_score,away_score&round_id=eq.${r.id}`),db<Pr[]>('predictions?select=match_id,player_id,home_score,away_score'),db<M[]>('matches?select=id,round_id,home_team,away_team,home_score,away_score')]);
 const rows=ps.map(p=>{const x=ms.map(m=>({m,pr:prs.find(z=>z.player_id===p.id&&z.match_id===m.id)})).filter(x=>x.pr) as {m:M;pr:Pr}[];return{p,score:x.reduce((s,x)=>s+pts(x.pr,x.m),0),exact:x.filter(x=>pts(x.pr,x.m)===3).length,correct:x.filter(x=>pts(x.pr,x.m)>0).length}}).sort((a,b)=>b.score-a.score||b.exact-a.exact||a.p.sort_order-b.p.sort_order)
 const facts:{priority:number;text:string}[]=[];const best=rows[0]?.score??0,w=rows.filter(x=>x.score===best);if(w.length===1)facts.push({priority:100,text:`🏆 <b>Герой тура — ${w[0].p.name}</b>: ${best} очк.${w[0].exact?` и 🎯 ${w[0].exact} точн.`:''}`});else facts.push({priority:95,text:`🤝 <b>Герои тура — ${w.map(x=>x.p.name).join(' · ')}</b>: по ${best} очк.`})
 const ex=Math.max(...rows.map(x=>x.exact));if(ex>0){const a=rows.filter(x=>x.exact===ex);facts.push({priority:90,text:`🎯 <b>Снайпер${a.length>1?'ы':''} тура:</b> ${a.map(x=>x.p.name).join(' · ')} — ${ex} точн${ex===1?'ый счёт':'ых счёта'}.`})}
 for(const m of ms){const picks=ps.map(p=>({p,pr:prs.find(x=>x.player_id===p.id&&x.match_id===m.id)})).filter(x=>x.pr) as {p:P;pr:Pr}[];if(!picks.length)continue;const scorers=picks.filter(x=>pts(x.pr,m)>0),actual=out(m.home_score,m.away_score);if(scorers.length===1)facts.push({priority:88,text:`🦸 <b>Один против всех:</b> ${scorers[0].p.name} единственный набрал очки в ${m.home_team} — ${m.away_team}.`});if(!scorers.length)facts.push({priority:82,text:`💀 <b>Кладбище прогнозов:</b> ${m.home_team} — ${m.away_team}, никто не набрал ни одного очка.`});
  const g=new Map<number,{p:P;pr:Pr}[]>();for(const x of picks){const o=out(x.pr.home_score,x.pr.away_score);g.set(o,[...(g.get(o)||[]),x])}const rank=[...g.entries()].sort((a,b)=>b[1].length-a[1].length);if(rank[0]&&rank[0][1].length>picks.length/2&&rank[0][0]!==actual)facts.push({priority:86,text:`🐑 <b>Стадный инстинкт подвёл:</b> ${rank[0][1].length}/${picks.length} ждали ${label(rank[0][0],m)}.`});if(rank.length===2&&rank[1][1].length===1&&rank[1][0]===actual)facts.push({priority:92,text:`🧠 <b>Против толпы:</b> ${rank[1][1][0].p.name} единственный выбрал верный исход ${m.home_team} — ${m.away_team}.`})}
 const predictedGoals=ms.flatMap(m=>prs.filter(p=>p.match_id===m.id)).reduce((s,p)=>s+p.home_score+p.away_score,0);const nPred=ms.reduce((s,m)=>s+prs.filter(p=>p.match_id===m.id).length,0);const realAvg=ms.length?ms.reduce((s,m)=>s+m.home_score+m.away_score,0)/ms.length:0,predAvg=nPred?predictedGoals/nPred:0;if(nPred)facts.push({priority:65,text:`⚽ <b>Голы:</b> ждали в среднем ${predAvg.toFixed(1)} за матч → получили ${realAvg.toFixed(1)}.`})
 const total=rows.reduce((s,x)=>s+x.score,0),avg=rows.length?total/rows.length:0;const prevRounds=new Set(allMs.filter(m=>m.round_id!==r.id&&m.home_score!=null).map(m=>m.round_id));if(prevRounds.size){const prevId=[...prevRounds].pop()!;const prev=ps.map(p=>allMs.filter(m=>m.round_id===prevId).reduce((s,m)=>{const pr=prs.find(x=>x.player_id===p.id&&x.match_id===m.id);return s+(pr?pts(pr,m):0)},0));const pa=prev.reduce((a,b)=>a+b,0)/prev.length;facts.push({priority:60,text:`📈 <b>Средний результат:</b> ${avg.toFixed(1)} очк. на игрока${avg>pa?` — выше прошлого тура (${pa.toFixed(1)})`:avg<pa?` — ниже прошлого тура (${pa.toFixed(1)})`:` — как в прошлом туре`}.`})}
 const chosen=facts.sort((a,b)=>b.priority-a.priority).slice(0,7);return[`📊 <b>Цифры тура ${r.round_number}</b>`,'',...chosen.map(x=>x.text)].join('\n\n')}
async function run(){const g=await group();if(!g)return{ok:false,reason:'no_group'};const rs=await db<R[]>('rounds?select=id,round_number&status=eq.finished&summary_sent_at=not.is.null&fun_stats_sent_at=is.null&order=round_number.asc&limit=3');let sent=0;for(const r of rs){await send(g,await digest(r));await db(`rounds?id=eq.${r.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({fun_stats_sent_at:new Date().toISOString()})});sent++}return{ok:true,sent}}
export async function GET(){try{return NextResponse.json(await run())}catch(e){console.error(e);return NextResponse.json({ok:false},{status:500})}}
